# DB container
db:  
  image: mysql
  env_file: .env
# Bundler data container to cache the gems installed
bundle:
  image: tianon/true
  volumes:
    - /bundle
# Web application container
web:
  build: .
  command: ./start.sh
  user: ruby
  volumes:
    - .:/myapp
  volumes_from:
    - bundle
  ports:
    - "3000:3000"
  links:
    - db
  env_file: .env
