db:  
  image: mysql
  environment:
    MYSQL_USER: web
    MYSQL_PASSWORD: letme1n
    MYSQL_ROOT_PASSWORD: letme1n
    MYSQL_DATABASE: web
web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    MYSQL_USER: web
    MYSQL_PASSWORD: letme1n
    MYSQL_DATABASE: web
